spring:
  profiles:
    group:
      "blue" : "blue"
      "green" : "green"
    default: "blue"
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: false
      show-sql: true
  datasource:
    # mariaDB setting
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ssafy605
    username: root
    password: root

---
spring:
  config:
    activate:
      on-profile: blue
server:
  port: 8085
---
spring:
  config:
    activate:
      on-profile: green
server:
  port: 8086