spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 'd7d7a42861b64d89868bc0f51679f971'
            client-secret: 'B2HOXLzUbeVup0jf6403Cuwx03niLQms'
            scope:
              - profile_nickname
              - account-email
              - profile-image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-authentication-method: POST
          naver:
            client-id: 'YN1WmgMqqE5dvT2tN9K1'
            client-secret: 'e8ZpMggadM'
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile-image
            client-name: Naver
          google:
            client-id: '451198103817-8b1cchldd6guatlfdg431gs119b0t8ad.apps.googleusercontent.com'
            client-secret: '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'
            redirect-uri: '{baseUrl}/login/{action}/oauth2/code/{registrationId}'
            scope: profile, email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oaut2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: false
      show-sql: true
  datasource:
    # mariaDB setting
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ssafy605
    username: root
    password: root
jwt:
  secret: wjdtjdenchlrhwhwjdtjdenchlrhwhwjdtjdenchlrhwhwjdtjdenchlrhwh

data:
  redis:
    host: localhost
    port: 6379