spring:
  data:
    redis:
#      host: j8a605.p.ssafy.io
      host: 3.39.209.108
      port: 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 8555e0c7360a81fde3a64b11b7635fd6
            client-secret: yj34MVMX2Dl8IZPqzHSym8dC1ek7ZeiS
            scope:
              - profile_nickname
              - account_email
              - profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST
          naver:
            client-id: YN1WmgMqqE5dvT2tN9K1
            client-secret: e8ZpMggadM
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-authentication-method: post
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          google:
            client-id: 451198103817-8b1cchldd6guatlfdg431gs119b0t8ad.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oaut2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: false
      show-sql: true
  datasource:
    # mariaDB setting
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://3.39.209.108:3306/ssafy605
#    url: jdbc:mariadb://j8a605.p.ssafy.io:3306/ssafy605
    username: root
    password: root
jwt:
  secret: wjdtjdenchlrhwhwjdtjdenchlrhwhwjdtjdenchlrhwhwjdtjdenchlrhwh


app:
  oauth2:
    authorizedRedirectUris:
      - exp://192.168.0.101:19000/oauth/redirect
