spring:
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: false
      show-sql: true
  datasource:
    # mariaDB setting
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.c4lgul6hmhxo.ap-northeast-2.rds.amazonaws.com:3306/ttarawa
    username: soo
    password: soo12345