spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 'd7d7a42861b64d89868bc0f51679f971'
            client-secret: 'B2HOXLzUbeVup0jf6403Cuwx03niLQms'
            scope:
              - profile_nickname
              - account-email
              - profile-image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-authentication-method: POST
          naver:
            client-id: YN1WmgMqqE5dvT2tN9K1
            client-secret: e8ZpMggadM
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile-image
            client-name: Naver
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: false
      show-sql: true
  datasource:
    # mariaDB setting
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ssafy605
    username: root
    password: root
jwt:
  secret: wjdtjdenchlrhwhwjdtjdenchlrhwhwjdtjdenchlrhwhwjdtjdenchlrhwh

data:
  redis:
    host: localhost
    port: 6379