version: '3.8'
networks:
  elk:
    driver: bridge
persistence:
  enabled: false
extraVolumes:
- name: data
  hostPath:
    path: /data/pv0001/
extraVolumeMounts:
- name: data
  mountPath: /usr/share/elasticsearch/data
extraInitContainers: |
   - name: create
     image: busybox:1.28
     command: ['mkdir', '-p', '/usr/share/elasticsearch/data/nodes/']
     securityContext:
       runAsUser: 0
     volumeMounts:
      - mountPath: /usr/share/elasticsearch/data
        name: data
   - name: file-permissions
     image: busybox:1.28
     command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
     securityContext:
        runAsUser: 0
     volumeMounts:
      - mountPath: /usr/share/elasticsearch/data
        name: data
        
services:
  # Elastic search 설정
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.10.1
    command: ['mkdir', '-p', '/usr/share/elasticsearch/data/nodes/']
    command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
    ports:
      - 9200:9200
      - 9300:9300
    volumes: 
      - ./elasticsearch:/usr/share/elasticsearch/data
    # Elastic search 계정정보
    environment: 
      discovery.type: single-node
      xpack.security.enabled: "true"
      xpack.security.transport.ssl.enabled: "true"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "ssafy605"
    networks:
      - elk

  # Logstash 설정
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.10.1
    ports:
      - 5000:5000
      - 9600:9600
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on: 
      - elasticsearch
    networks:
      - elk

  # Kibana 설정
  kibana:
    container_name: kibana
    image: kibana:7.10.1
    ports: 
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk
      
  backend:
    build:
      context: ./ttarawa
      dockerfile: Dockerfile
      args:
        SERVER_MODE: test
    ports:
      - "8081:8080"
    volumes:
      - ./ttarawa:/app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://j8a605.p.ssafy.io:3306/ssafy605
      - SPRING_DATASOURCE_USERNAME=ssafy605
      - SPRING_DATASOURCE_PASSWORD=ssafy605

volumes:
  db-data:
