version: '3.8'

services:
    db:
        image: mariadb
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=ssafy605
            - MYSQL_DATABASE=ssafy605
            - MYSQL_USER=ssafy605
            - MYSQL_PASSWORD=ssafy605
        ports:
            - "3306:3306"
    redis:
        image: redis:6.2.6-alpine
        ports:
            - "6379:6379"
        volumes:
            - /host/system/path:/container/path
    backend:
        build:
            context: ./ttarawa
            dockerfile: Dockerfile
            args:
                SERVER_MODE: deploy
        ports:
            - "8080:8080"
        volumes: 
            - ./ttarawa:/app
        depends_on:
            - db
            - redis
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mariadb://j8a605.p.ssafy.io:3306/ssafy605
            - SPRING_DATASOURCE_USERNAME=ssafy605
            - SPRING_DATASOURCE_PASSWORD=ssafy605
            - REDIS_HOST=redis
    nginx:
        container_name: nginx
        build: ./.nginx
        depends_on:
            - backend
        volumes:
            - .nginx/conf.d:/etc/nginx/conf.d
            - .nginx/zerossl:/var/www/zerossl/.well-known/pki-validation
            - .nginx/cert:/cert
        ports:
            - 80:80
            - 443:443
  
volumes:
    db-data:

