version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      args:
        SERVER_MODE: blue
    image: app:0.2
    container_name: app_green
    environment:
      - "spring_profiles_active=green"
    ports:
      - "8086:8086"